set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-open'

set -g prefix C-SPACE
unbind C-b
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on
set -g mouse on

setenv -g tmux_magenta "#a48cf2"
setenv -g tmux_magenta_dark "#bf4f8e"
setenv -g tmux_pink "#f265b5"
setenv -g tmux_cyan "#04d1f9"
setenv -g tmux_orange "#f7c67f"
setenv -g tmux_yellow "#f1fc79"
setenv -g tmux_green "#37f499"
setenv -g tmux_red "#f16c75"
setenv -g tmux_fg_inactive "#7081d0"
setenv -g tmux_bg_dark "#171928"

set -g message-style "bg=${tmux_bg_dark} fg=white, bold" # remove yellow message line
set -g mode-style "bg=${tmux_bg_dark} fg=white, bold" # session selection
set -g pane-border-style "fg=${tmux_fg_inactive}"
set -g pane-active-border-style "fg=${tmux_magenta}"

# --- Status ---
set -g status-position top
set -g status-keys emacs
set -g status-style "bg=default fg=${tmux_fg_inactive}"
set -g status-left ""

set -g status-justify right
set -g window-status-format "#I:#W"
set -g window-status-current-format "#[fg=${tmux_magenta}, bold]#I:#W"

set -g status-right " #[fg=${tmux_green} bold]| #{?client_prefix,#[fg=${tmux_magenta_dark} bold reverse],#[fg=${tmux_magenta_dark} bold]}#S#[noreverse]"

# --- Keybindings ---
setw -g mode-keys vi;
unbind -T copy-mode    MouseDragEnd1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi Escape if -F '#{selection_present}' 'send -X clear-selection' 'send -X cancel'
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


bind C-Space send-prefix
bind r source-file "~/.config/tmux/tmux.conf"; display-message "#[fg=cyan bold]Config Reloaded" # source config
bind b set -g status # toggle status
bind g neww -n "git" -S lazygit # lg in cwd
bind G run "~/bin/open-github.sh"
bind c new-window -c "#{pane_current_path}" # open in cwd
bind "|" split-window -hc "#{pane_current_path}" # mod split hrz to match nvim
bind "\\" split-window -vc "#{pane_current_path}" # mod split vir to match nvim
bind j choose-window 'join-pane -h -s "%%"' # join horizontaly
bind J choose-window 'join-pane -s "%%"' # join vertically
bind C-p previous-window
bind C-n next-window

run '~/.config/tmux/plugins/tpm/tpm'
