
# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      ██████╗  ██████╗██╗  ██╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔═══██╗██╔════╝██║ ██╔╝
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ██║   ██║██║     █████╔╝ 
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██║   ██║██║     ██╔═██╗ 
# ██║  ██║   ██║   ██║     ██║  ██║███████╗╚██████╔╝╚██████╗██║  ██╗
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝

$fn_greet=echo "<i> Hi $USER :) </i>"
#$wall = $hyprlockDir/wallpapers/1.jpg
$wall = $HOME/.local/share/wallpapers/nausicaa002.jpg

$color_light_pink = rgba(249, 155, 196, 1)
$color0 = rgba(61, 66, 64, 1) # "black" (dark grey)
$color1 = rgba(236, 131, 154, 1) #red
$color2 = rgba(136, 212, 201, 1) #green
$color4 = rgba(222, 177, 123, 1) #yellow
$color5 = rgba(137, 166, 237, 1) #blue
$color6 = rgba(193, 161, 237, 1) #purple
$color7 = rgba(133, 201, 245, 1) #cyan
$color8 = rgba(190, 198, 236, 1) #white



# GENERAL
general {
  no_fade_in = true
  grace = 1
  disable_loading_bar = false
  immediate_render = true
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

# BACKGROUND
background {
    monitor = 
    path = $wall
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
    vibrancy_darkness = 0
    color = $color0
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    # color = rgba(255, 255, 255, 1)
    color = $color_light_pink
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.2
    font_size = 150
    font_family = AlfaSlabOne 
    position = 0, -250
    halign = center
    valign = top
    zindex = 5
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    # color = rgba(255, 255, 255, 1)
    color = $color7
    font_size = 150
    font_family = AlfaSlabOne
    position = 0, -420
    halign = center
    valign = top
    zindex = 5
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    # color = rgba(255, 255, 255, 1)
    color = $color8
    font_size = 14
    font_family = AlfaSlabOne #JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -650
    halign = center
    valign = top
    zindex = 5
}

# INPUT FIELD
input-field {
    monitor = #eDP-1
    size = 250, 80
    outline_thickness = 0
    outer_color = rgba(0, 0, 0, 0)
    dots_size = 0.1 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(0, 0, 0, 0) #$primary_3_rgba
    font_color = $color7 #rgba(200, 200, 200, 0.8)
    fade_on_empty = false
    placeholder_text =<i>:P</i>
    hide_input = false
    fail_color = $color1
    fail_text = <i> X </i>
    position = 0, -370
    halign = center
    valign = center
    zindex = 20
}

# USER
label {
    monitor = eDP-1
    #text = cmd[update:60000] echo "Good $(date +"%-I" | awk '{if ($1 < 12) print "morning"; else print "evening"}') $(echo ${USER} | tr '[:lower:]' '[:upper:]' )"
    text = cmd[update:60000] $fn_greet 
    color = $color8
    font_size = 17
    font_family = JetBrains Mono Nerd Font Mono
    position = 0, -310
    halign = center
    valign = center
}
