
# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  █████╗ ██████╗ ███████╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗  ██████╔╝
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
# ██║  ██║   ██║   ██║     ██║  ██║██║     ██║  ██║██║     ███████╗██║  ██║
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝

ipc = true
splash = false

wallpaper {
  monitor =
  path = ~/.local/share/wallpapers/active/pompokoTree_palettized_Eldritch.png
  fit_mode = fill
}
