
# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  █████╗ ██████╗ ███████╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗  ██████╔╝
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
# ██║  ██║   ██║   ██║     ██║  ██║██║     ██║  ██║██║     ███████╗██║  ██║
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝

preload = ~/.local/share/wallpapers/active/pompokoTree_palettized_Eldritch.png
wallpaper = , ~/.local/share/wallpapers/active/pompokoTree_palettized_Eldritch.png
