---@type LazySpec
return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		keys = { -- Lazy keymap table
			{
				"<leader>?",
				function()
					require("which-key").show({ global = false })
				end,
				desc = "Local Keymaps",
			},
		},
		opts = {
			win = {
				width = { min = 30, max = 60 },
				height = { min = 4, max = 0.75 },
				padding = { 0, 1 },
				col = 1,
				row = -1,
				border = "single",
				title = true,
				title_pos = "left",
			},
			layout = {
				width = { min = 30 },
			},
			keys = { -- which-key keymap table
				scroll_down = "<a-down>",
				scroll_up = "<a-up>",
			},
			sort = { "alphanum", "local", "order" },
			icons = {
				colors = true, -- (1 = use mini.icon colors)

				keys = { -- which-key key icons
					Up = " ",
					Down = " ",
					Left = " ",
					Right = " ",
					C = "󰘴 ",
					M = "󰘵 ",
					D = "󰘳 ",
					S = "󰘶 ",
					CR = "󰌑 ",
					Esc = "󱊷 ",
					ScrollWheelDown = "󱕐 ",
					ScrollWheelUp = "󱕑 ",
					NL = "󰌑 ",
					BS = "󰁮",
					Space = "󱁐 ",
					Tab = "󰌒 ",
					F1 = "󱊫",
					F2 = "󱊬",
					F3 = "󱊭",
					F4 = "󱊮",
					F5 = "󱊯",
					F6 = "󱊰",
					F7 = "󱊱",
					F8 = "󱊲",
					F9 = "󱊳",
					F10 = "󱊴",
					F11 = "󱊵",
					F12 = "󱊶",
				},

				rules = {
					{ plugin = "fzf-lua", cat = "filetype", name = "fzf" },
					{ plugin = "neo-tree.nvim", cat = "filetype", name = "neo-tree" },
					{ plugin = "octo.nvim", cat = "filetype", name = "git" },
					{ plugin = "yanky.nvim", icon = "󰅇", color = "yellow" },
					{ plugin = "zen-mode.nvim", icon = "󱅻 ", color = "cyan" },
					{ plugin = "telescope.nvim", pattern = "telescope", icon = "", color = "blue" },
					{ plugin = "trouble.nvim", cat = "filetype", name = "trouble" },
					{ plugin = "todo-comments.nvim", cat = "file", name = "TODO" },
					{ plugin = "grapple.nvim", pattern = "grapple", icon = "󰛢", color = "azure" },
					{ plugin = "nvim-spectre", icon = "󰛔 ", color = "blue" },
					{ plugin = "grug-far.nvim", pattern = "grug", icon = "󰛔 ", color = "blue" },
					{ plugin = "noice.nvim", pattern = "noice", icon = "󰈸", color = "orange" },
					{ plugin = "persistence.nvim", icon = " ", color = "azure" },
					{ plugin = "neotest", cat = "filetype", name = "neotest-summary" },
					{ plugin = "lazy.nvim", cat = "filetype", name = "lazy" },
					{ plugin = "snacks.nvim", icon = "󱥰 ", color = "purple" },
					{ plugin = "refactoring.nvim", pattern = "refactor", icon = " ", color = "cyan" },
					{ pattern = "profiler", icon = "⚡", color = "orange" },
					{ plugin = "CopilotChat.nvim", icon = " ", color = "orange" },
					{ pattern = "close", icon = "󰅙 ", color = "red" },
					{ pattern = "command", icon = "󰘳 ", color = "blue" },
					{ pattern = "code action", icon = "󰘳 ", color = "blue" },
					{ pattern = "location", icon = " " },
					{ pattern = "loclist", icon = " " },
					{ pattern = "%f[%a]git", cat = "filetype", name = "git" },
					{ pattern = "terminal", icon = " ", color = "red" },
					{ pattern = "find", icon = " ", color = "green" },
					{ pattern = "search", icon = " ", color = "green" },
					{ pattern = "horizontal", icon = "󱋰 ", color = "green" },
					{ pattern = "vertical", icon = "󱋱 ", color = "green" },
					{ pattern = "grep", icon = "󰾹 ", color = "green" },
					{ pattern = "word", icon = "󰾹 ", color = "green" },
					{ pattern = "test", cat = "filetype", name = "neotest-summary" },
					{ pattern = "lazy", cat = "filetype", name = "lazy" },
					{ pattern = "symbol", icon = " ", color = "cyan" },
					{ pattern = "format", icon = "󰉼 ", color = "cyan" },
					{ pattern = "buffer", icon = "󰈔", color = "cyan" },
					{ pattern = "files", icon = "󰉋 ", color = "cyan" },
					{ pattern = "file", icon = "󰈔", color = "cyan" },
					{ pattern = "window", icon = " ", color = "blue" },
					{ pattern = "language", icon = " ", color = "green" },
					{ pattern = "diagnostic", icon = " ", color = "red" },
					{ pattern = "reference", icon = " ", color = "red" },
					{ pattern = "definition", icon = " ", color = "cyan" },
					{ pattern = "implementation", icon = " ", color = "green" },
					{ pattern = "keymap", icon = " ", color = "grey" },
					{ pattern = "debug", icon = "󰃤 ", color = "red" },
					{ pattern = "code", icon = " ", color = "orange" },
					{ pattern = "notif", icon = "󰵅 ", color = "blue" },
					{ pattern = "toggle", icon = " ", color = "orange" },
					{ pattern = "session", icon = " ", color = "azure" },
					{ pattern = "exit", icon = "󰈆 ", color = "red" },
					{ pattern = "quit", icon = "󰈆 ", color = "red" },
					{ pattern = "tab", icon = "󰓩 ", color = "purple" },
					{ pattern = "%f[%a]ai", icon = " ", color = "green" },
					{ pattern = "ui", icon = "󰙵 ", color = "cyan" },
				},
			},
		},
	},
}
