# comment.line.number-sign

[section]                  # entity.name.section
number = 42                # constant.numeric
color = "#ff0000"          # constant.other, string.quoted.double
enabled = true             # constant.language

option: value              # entity.attribute-name, variable.other
