enable_audio_bell no

font_size 10.0
window_padding_width 14

cursor_trail 1
cursor_trail_color #7081d0

allow_remote_control yes

background_opacity 0.9

# BEGIN_KITTY_THEME
# include Catppuccin-Mocha.conf
include Eldritch.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family='Maple Mono NF CN' style=Light features=+zero
bold_font        family='Maple Mono NF CN' style=Bold features=+zero
italic_font      family='Maple Mono NF CN' style='Medium Italic' features=+zero
bold_italic_font family='Maple Mono NF CN' style='SemiBold Italic' features=+zero
# END_KITTY_FONTS
